baseurl = "https://hipersuperultra.github.com/cpp"
languageCode = "en"
title = "hipersuperultra's cpp log"
theme = "kiss"
copyright = "&copy; <a href=\"https://hipersuperultra.github.com\">hipersuperultra</a> 2019"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

# publishDir = "docs" # using gh-pages branch instead

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "hipersuperultra" # Author full name
authorEmail = "OH MY DOG" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
homeTitle = "hipersuperultra's cpp log" # Title for home page
# poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
# disqusOnDemand = true  # Load Disqus comments on click

[params.social]
github = "hipersuperultra"
instagram = "hipersuperultra"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","instagram"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true
